### ISSUE TITLE
URL to examples/hello_world not found

### ISSUE THREAD

**Issue by lvdh** [data-intuitive/viash_docs#1]
Dear team,

On the following docs page:

http://www.data-intuitive.com/viash_docs/getting_started/example_bash/#demonstration

A link named 'examples/hello_world' points to the following URL, for which I receive a not found error:

http://www.data-intuitive.com/viash_docs/getting_started/example_bash/examples/hello_world

Perhaps this might be the intended target page?

http://www.data-intuitive.com/viash_docs/examples/hello_world

Putting this in as an issue as I'm not entirely sure which URL would be the right one.

Cheers,
Laurens

**Comment by BlackDragonBE** [comment]
Fixed in my branch, will be pushed to master soon. 
The correct path is https://github.com/data-intuitive/viash_docs/tree/master/examples/hello_world

**Comment by rcannood** [comment]
Thanks, merged into master.
