### ISSUE TITLE
Add markdown documentation

### ISSUE THREAD

**Issue by rcannood** [data-intuitive/viash_docs#2]
- [x] Getting started
  * [x] Installation
  * [ ] Supported languages
  * [x] Hello World (Bash)
  * [ ] Hello World (Python) (Needs work)
  * [ ] Hello World (R) (Needs work)
  * [ ] Hello World (Scala) (non-existent)
  * [ ] Hello World (Javascript) (non-existent)
- [x] Creating components
  * [ ] Creating a Bash component (Needs major update)  
  * [ ] Creating a Python component (Needs major update)
  * [ ] Creating an R component (Needs major update)
  * [ ] Creating a Scala component (non-existent)
  * [ ] Creating a Javascript component (non-existent)
- [x] Commands
  * [x] viash run
  * [x] viash build
  * [x] viash test
  * [x] viash ns build
  * [x] viash ns test
  * [x] viash ns list
  * [x] viash config view
- [ ] Scripting variables
  * [ ] resources_dir
- [x] Config
  * [x] Functionality
  * [x] Native platform
  * [x] Docker platform
  * [ ] Nextflow platform
  * [x] File formats
- [x] Config mods
  * [ ] ?
- [ ] Good practices
  * [ ] Namespaces
  * [ ] Reproducibility
  * [ ] Testing
  * [ ] Workflow
  * [ ] CI
- [ ] Frequently asked questions 
- [x] Version history
  * [x] viash v0.0.1
  * [x] viash v0.1.0
  * [x] viash v0.2.0
  * [x] viash v0.2.1
  * [x] viash v0.2.2

**Comment by BlackDragonBE** [comment]
Updated TODO list.

**Comment by rcannood** [comment]
Please also add a 'Frequently asked questions' page. Whenever we get a question from a user who doesn't know how to tackle a certain problem, we can add it to the FAQ.

For example:

### Running a component causes error 'Unable to find image'

Depending on how an executable was created, a Docker container might not have been created. 

To solve this issue, run the executable with a `---setup` flag attached. This will 
automatically build the Docker container for you. 

```
$ target/docker/foo/foo ---setup
> docker build -t foo:0.0.1 /home/rcannood/workspace/viash_temp/viashsetupdocker-foo-KeBjFs
```

Or when working with `viash run`:

```
$ viash run src/mnn/config.vsh.yaml -- ---setup
> docker build -t foo:0.0.1 /home/rcannood/workspace/viash_temp/viashsetupdocker-foo-KeBjFs
```

**Comment by BlackDragonBE** [comment]
@rcannood Great suggestion! Added FAQ page in my branch.

**Comment by rcannood** [comment]
Closing this issue because the docs moved elsewhere.
